uploads = []
generated = []

[[outputs]]
id = "6fPm6d2y16LtKc65Eic85"
uri = "file://luldown-code.tar.gz"
type = "unspecified"
title = "⬇️ LulDown — Saari Files Download Karo"

[[outputs]]
id = "ewgq8OXTWHgIuq8r9YUZP"
uri = "file://luldown-src.tar.gz"
type = "unspecified"
title = "⬇️ LulDown — Source Code (124KB)"
